name: "Nette Tester"

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [8.2, 8.3]

            fail-fast: false

        name: Nette Tester - ${{matrix.php}}

        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: xdebug

            - run: make tester

            - uses: actions/upload-artifact@v4
              with:
                  name: coverage-php${{ matrix.php }}
                  path: tests/coverage.html
